---
apiVersion: v1
kind: Service
metadata:
  name: bootiful-k8s-service
  labels:
    app: bootiful-k8s-service
spec:
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: bootiful-k8s-app
  type: NodePort
