apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: bootiful-k-s
build:
  artifacts:
  - image: docker.io/odrianoaliveira/bootiful-k8s-app
    jib:
      project: com.signavio:bootiful-k8s
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
