apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: order-management
build:
  artifacts:
    - image: docker.io/odrianoaliveira/order-management-app
      jib:
        project: tech.adriano:order-management
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
