---
apiVersion: v1
kind: Service
metadata:
  name: order-management-service
  labels:
    app: order-management-service
spec:
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: order-management-app
  type: NodePort
